[package]
name = "macro_deez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-dynamodb = "0.28.0"
macro_deez_derive = { version = "0.1.0", path = "macro_deez_derive" }
